[project]
authors = ["Mu Xian Ming <marsmxm@gmail.com>"]
channels = ["https://conda.modular.com/max", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community", "conda-forge"]
description = "Add a short description here"
name = "xgboost-learn"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
python = "3.11.*"
xgboost = ">=2.1.3,<3"
